repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]
        exclude: ^tests/examples/
      - id: check-toml
      - id: check-json
      # Hook shows incompatibility with ipynb files
      #  - id: pretty-format-json
      #    args: [--autofix]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.4
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
        exclude: ^contrib/
      # Run the formatter.
      - id: ruff-format
        exclude: ^contrib/
